### ISSUE TITLE
New rule: scoped but no injectable

### ISSUE THREAD

**Issue by BraisGabin** [WhosNickDoglio/dagger-rules#151]
I find some instances of this error on the project I work on. A class is annotated with `@Singleton` (or any other scoped annotation) but its constructor is not annotated with `@Inject`.

The singleton annotation does nothing there and the compiler doesn't warn you.

Sample:

```kotlin
@Singleton // This annotation does nothing! But when you read the code you may think it does
Class Foo {}
```

**Comment by WhosNickDoglio** [comment]
Great idea! I can definitely work on adding that. 

Just dropping some thoughts on this later when I work on it:

- Support Anvils [SingleIn](https://github.com/square/anvil/blob/main/annotations-optional/src/main/java/com/squareup/anvil/annotations/optional/SingleIn.kt) & [Hilts scopes](https://dagger.dev/hilt/components)
- Make this configurable for custom scopes

**Comment by WhosNickDoglio** [comment]
> All the custom scopes should have one thing in common. They are annotated with @Scope that should be enoght.

You are correct! I was playing around with this idea this morning and figured out I can just check for the `@Scope` annotation, I'll have something up today or tomorrow, just need to write tests and documentation. 

> I'm not sure how @AssistedInject and scopes work... Maybe that's other thing to check.

Scopes do not work with `@AssistedInject` which sounds like this could be another rule 😄
